<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell210221" failures="1" tests="5" name="Listener Test Case" time="0.22" errors="0" timestamp="2023-12-20T14:48:01 GMT">
  <testcase classname="com.testng.listeners.SampleTestClass" name="testFour" time="0.031">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.testng.listeners.SampleTestClass" name="testGetData" time="0.006"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testGetData" time="0.003"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testOne" time="0.002"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testThree" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testng.listeners.SampleTestClass.testThree(SampleTestClass.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener Test Case -->
